### ISSUE TITLE
clip bbox issue

### ISSUE THREAD

**Issue by ifzhang** [JudasDie/SOTS#36]
Thanks for your wonderful work! I find that on MOTChallenge dataset clipping bbox may lead to degraded results. I comment all the clip bbox operations in https://github.com/JudasDie/SOTS/blob/master/lib/dataset/cstrack.py and meet the following training error. Can you help me fix this? Thanks very much. @H11zang 

Traceback (most recent call last):                                                                                                                                                              
  File "train_cstrack.py", line 517, in <module>                                                                                                                                                
    train(hyp, opt, device, tb_writer)                                                                                                                                                          
  File "train_cstrack.py", line 319, in train                                                                                                                                                   
    loss, loss_items = mot_loss(pred, targets.to(device), model)  # scaled by batch_size                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                    
    result = self.forward(*input, **kwargs)                                                                                                                                                     
  File "/opt/tiger/demo/SOTS/tracking/../lib/core/mot/base_trainer.py", line 355, in forward                                                                                                    
    giou = bbox_iou(pbox.T, tbox[i], x1y1x2y2=False, CIoU=True)  # giou(prediction, target)                                                                                                     
  File "/opt/tiger/demo/SOTS/tracking/../lib/core/mot/base_trainer.py", line 67, in bbox_iou                                                                                                    
    w2, h2 = b2_x2 - b2_x1, b2_y2 - b2_y1                                                                                                                                                       
RuntimeError: CUDA error: device-side assert triggered                                                                                                                                          
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [79,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [79,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

**Comment by H11zang** [comment]
Thanks for your attention. We have solved this problem in the new code and will release it soon. Moreover, we have modified CSTrack for this problem in the version for Panda. You can see https://github.com/JudasDie/SOTS/blob/master/lib/dataset/cstrack_panda.py for more details.

**Comment by ifzhang** [comment]
I have fixed the bug and opened a simple PR. The MOTA increases about 6 points when training on mot17_hf.train and evaluating on mot17_hf.val. Also looking forward to your new version :)

**Comment by H11zang** [comment]
OK, Thx. :)
